---
name: destroy infrastructure
on:
  workflow_dispatch
jobs:
  destroy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: terraform destroy
        uses: hashicorp/terraform-github-actions@v2.5.0
        with:
          tf_actions_version: '1.13.3'
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: './terraform'
          tf_actions_auto_approve: 'true'
          tf_actions_cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
